### ISSUE TITLE
SVG Import Roadmap

### ISSUE THREAD

**Issue by scribblemaniac** [scribblemaniac/vpaint#1]
This is where I will be keeping track of all of the things that need to be completed for the svg import feature. Below are some of the things I plan on supporting. This list is currently incomplete, I will add new sections as I come across them in the W3 specifications. Currently, we are primarily  aiming to support SVG 1.1.

Tags:
- [x] rect
- [x] circle
- [x] ellipse
- [x] line
- [x] polyline
- [x] polygon
- [ ] g
- [ ] animate (basic things like color, translation, etc.)
- [x] path (with faux bezier)

Presentation attributes:
- [ ] fill (Partially complete. Missing color tag support and inherit)
- [ ] stroke (Partially complete. Missing color tag support and inherit)
- [x] opacity
- [x] stroke-opacity
- [x] fill-opacity
- [ ] visibility
- [x] stroke-width
- [ ] fill-rule

Other stuff:
- [ ] style
- [ ] Soft corner detection
